theme: minimal-mistakes-jekyll
title: Swift Travel
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

minimal_mistakes_skin: "contrast"
logo: "/assets/logo/swift.png"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: true
      toc: true
