theme: minimal-mistakes-jekyll
title: Swift Travel
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

logo: "/assets/logo/swift.png"

defaults:
  # _pages
  - scope:
      path: ""
    values:
      layout: single
      toc: true
