name: live_route
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.0-0.0.beta <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  swift_travel:
    path: ../../app
  freezed_annotation:
  geolocator:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  freezed:
  json_serializable:
  lint: ^2.0.1

flutter: null
